// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkwEVEmkOIZfBWHW2kODFY5pVUVCfLOds',
    appId: '1:855995089769:web:071d6e5854bf075fbeb3f8',
    messagingSenderId: '855995089769',
    projectId: 'despensa-inteligente-c1f9d',
    authDomain: 'despensa-inteligente-c1f9d.firebaseapp.com',
    storageBucket: 'despensa-inteligente-c1f9d.firebasestorage.app',
    measurementId: 'G-TH6KWCN1GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfIcQz9suOPxo7_6UlX0_K5UBzqNKU48',
    appId: '1:855995089769:android:4e16cb687e58423abeb3f8',
    messagingSenderId: '855995089769',
    projectId: 'despensa-inteligente-c1f9d',
    storageBucket: 'despensa-inteligente-c1f9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdEtt5Cdnc_XgbesyEgO7dYKX0bT784OE',
    appId: '1:855995089769:ios:834b8b7f20d01b0cbeb3f8',
    messagingSenderId: '855995089769',
    projectId: 'despensa-inteligente-c1f9d',
    storageBucket: 'despensa-inteligente-c1f9d.firebasestorage.app',
    iosBundleId: 'com.webiados.despensainteligente.despensaInteligente',
  );
}
